// frontend_angular/src/app/shared/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <aside class="sidebar">
      <div class="sidebar-header">
        <h1 class="logo">📋 HRMS Lite</h1>
      </div>
      
      <nav class="sidebar-nav">
        <a routerLink="/dashboard" routerLinkActive="active" class="nav-item">
          <span class="material-icons">dashboard</span>
          <span>Dashboard</span>
        </a>
        <a routerLink="/employees" routerLinkActive="active" class="nav-item">
          <span class="material-icons">people</span>
          <span>Employees</span>
        </a>
        <a routerLink="/attendance" routerLinkActive="active" class="nav-item">
          <span class="material-icons">calendar_today</span>
          <span>Attendance</span>
        </a>
      </nav>
      
      <div class="sidebar-footer">
        <p>HRMS Lite v1.0.0</p>
      </div>
    </aside>
  `,
  styles: [`
    .sidebar {
      position: fixed;
      left: 0;
      top: 0;
      bottom: 0;
      width: var(--sidebar-width);
      background: white;
      border-right: 1px solid var(--gray-200);
      display: flex;
      flex-direction: column;
      z-index: 100;
    }
    
    .sidebar-header {
      height: var(--navbar-height);
      display: flex;
      align-items: center;
      padding: 0 1.5rem;
      border-bottom: 1px solid var(--gray-200);
    }
    
    .logo {
      font-size: 1.25rem;
      font-weight: 700;
      color: var(--primary-color);
    }
    
    .sidebar-nav {
      flex: 1;
      padding: 1rem;
    }
    
    .nav-item {
      display: flex;
      align-items: center;
      gap: 0.75rem;
      padding: 0.75rem 1rem;
      border-radius: 8px;
      color: var(--gray-600);
      font-weight: 500;
      margin-bottom: 0.25rem;
      transition: all 0.2s;
    }
    
    .nav-item:hover {
      background: var(--gray-100);
      color: var(--gray-800);
    }
    
    .nav-item.active {
      background: #eff6ff;
      color: var(--primary-color);
    }
    
    .nav-item .material-icons {
      font-size: 1.25rem;
    }
    
    .sidebar-footer {
      padding: 1rem 1.5rem;
      border-top: 1px solid var(--gray-200);
      text-align: center;
    }
    
    .sidebar-footer p {
      font-size: 0.75rem;
      color: var(--gray-500);
    }
    
    @media (max-width: 768px) {
      .sidebar {
        display: none;
      }
    }
  `]
})
export class SidebarComponent {}

// frontend/src/components/common/Sidebar.jsx
import { Link, useLocation } from 'react-router-dom';
import {
  Box,
  Flex,
  VStack,
  Text,
  Icon,
  useColorModeValue,
  Heading,
  Divider,
} from '@chakra-ui/react';
import { FiHome, FiUsers, FiCalendar } from 'react-icons/fi';

const navItems = [
  { name: 'Dashboard', path: '/', icon: FiHome },
  { name: 'Employees', path: '/employees', icon: FiUsers },
  { name: 'Attendance', path: '/attendance', icon: FiCalendar },
];

function Sidebar() {
  const location = useLocation();
  const bgColor = useColorModeValue('white', 'gray.800');
  const borderColor = useColorModeValue('gray.200', 'gray.700');
  const activeBg = useColorModeValue('blue.50', 'blue.900');
  const activeColor = useColorModeValue('blue.600', 'blue.200');

  return (
    <Box
      as="nav"
      pos="fixed"
      left={0}
      top={0}
      h="100vh"
      w="240px"
      bg={bgColor}
      borderRight="1px"
      borderColor={borderColor}
      display={{ base: 'none', md: 'block' }}
      zIndex={100}
    >
      {/* Logo */}
      <Flex h="64px" alignItems="center" px={6} borderBottom="1px" borderColor={borderColor}>
        <Heading size="md" color="blue.600" fontWeight="bold">
          📋 HRMS Lite
        </Heading>
      </Flex>

      {/* Navigation Items */}
      <VStack spacing={1} align="stretch" p={4}>
        {navItems.map((item) => {
          const isActive = location.pathname === item.path;
          return (
            <Link key={item.path} to={item.path}>
              <Flex
                align="center"
                px={4}
                py={3}
                borderRadius="lg"
                cursor="pointer"
                bg={isActive ? activeBg : 'transparent'}
                color={isActive ? activeColor : 'gray.600'}
                fontWeight={isActive ? 'semibold' : 'medium'}
                transition="all 0.2s"
                _hover={{
                  bg: isActive ? activeBg : 'gray.100',
                  color: isActive ? activeColor : 'gray.800',
                }}
              >
                <Icon as={item.icon} boxSize={5} mr={3} />
                <Text fontSize="sm">{item.name}</Text>
              </Flex>
            </Link>
          );
        })}
      </VStack>

      {/* Footer */}
      <Box pos="absolute" bottom={0} left={0} right={0} p={4}>
        <Divider mb={4} />
        <Text fontSize="xs" color="gray.500" textAlign="center">
          HRMS Lite v1.0.0
        </Text>
      </Box>
    </Box>
  );
}

export default Sidebar;
